name: Inputs Demo
on:
  workflow_dispatch:
    inputs:
      name:
         description: "Enter your name"
         required: true
         default: "DevOps Engineer"
      env:
        description: 'Enter environment (dev/test/prod)'
        required: true
        type: Environment
    run_tests:
        description: 'Run test cases?'
        required: true
        type: boolean
        default: true

      build_type:
        description: 'Select build type'
        required: true
        type: choice
        options:
          - debug
          - release
      version:
        description: 'Enter version'
        required: true
        default: '1.0.0'

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print User Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.env }}"
          echo "Version: ${{ github.event.inputs.version }}"